doc/chapters/4-graduation-thesis.tex
doc/doc.tex
wiki/Guide/3-Templates/Final-Graduation-Thesis.md

在wiki的guide中的毕业设计部分，加入了如何在文中插入定理的说明。

Add introduction of theorem environments in Wiki/Doc

---

.gitignore
Makefile
README-en.md
README.md
bithesis.dtx
bithesis.ins

- Bump license version.
- Refine build script.
- Add back English version readme and contribution guide.

V2.0.0 enhancement.

---

.github/workflows/main.yml
Makefile
bithesis.dtx
bithesis.ins

See: https://github.com/BIT-thesis/LaTeX-template
Related: #101

合并研究生学位论文模板

---

templates/paper-translation/main.tex
templates/undergraduate-thesis/main.tex

feat: give a workaround to redefine page head.

---

bithesis.dtx
templates/lab-report/main.tex

Provide bibliography in LabReport template.

---

templates/undergraduate-thesis/misc/5_appendix.tex

fix: 修复本科毕设的附录编号格式

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/graduate-thesis/misc/3_appendices.tex
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

feat: support chapter level appendices.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/graduate-thesis/chapters/abstract.tex
templates/graduate-thesis/chapters/chapter2.tex
templates/graduate-thesis/main.tex
templates/graduate-thesis/misc/0_symbols.tex
templates/graduate-thesis/misc/3_appendices.tex
templates/lab-report/bitreport.cls
templates/paper-translation/bithesis.cls
templates/presentation-slide/bitbeamer.cls
templates/undergraduate-proposal-report/bitreport.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

Refactor and bug fixes.

---

.github/workflows/test.yaml
CHANGELOG.md
README.md
bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/graduate-thesis/main.tex
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

v3.0.2 bug fixes

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix(bithesis): fix wrong bookmarks in appendix.

---

templates/graduate-thesis/README.md
tests/doctor-thesis/README.md

chore: fix typo.

---

.github/ISSUE_TEMPLATE/bug-report-ZH.yaml

chore(workflow): add missing field in the issue template.

---

bithesis.dtx

gobble=4 will ignore four characters.

fix(docs): increase Indent.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/graduate-thesis/main.tex
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

Preview: [main.pdf](https://github.com/BITNP/BIThesis/files/10693639/main.pdf)

fix: chapters now `openany` in twoside mode.

---

CHANGELOG.md
bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/lab-report/bitreport.cls
templates/paper-translation/bithesis.cls
templates/presentation-slide/bitbeamer.cls
templates/undergraduate-proposal-report/bitreport.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

Preparations for v3.4.0

---

templates/graduate-thesis/reference/main.bib
templates/paper-translation/misc/ref.bib

fix: fix invalid date fields in bibs.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: turn on AutoFakeBold and AutoFakeSlant in xeCJK.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: add options & fine-tune AutoFakeBold.

---

README.md
bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: add an english option to enable english mode.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/graduate-thesis/main.tex
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

feat: align content to top by default.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: make listoffigure & listoftable align with the old template.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

`listofx` will not clear page by default.

fix: clear page at start of `\mainmatter`.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: fix the skip of subsubsection.

---

templates/paper-translation/main.tex
templates/undergraduate-thesis/main.tex

templates/undergraduate-thesis/main.tex

fix: 本科毕设&文献翻译封面添加班号字段

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

refactor: try fix \MakeOriginality in the plagiarism check.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: graduate-thesis indent is larger than normal.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: typo fix.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls
tests/autorefs/main.tex

fix: add autoref label for figure(fig),table(tab),euqation(equ)

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: fix non-effective listings numbering.

---

.github/workflows/release.yml
bithesis.dtx

Revert "Add *.cls into Release"

---

bithesis.dtx

在文档中添加了 WSL 用户该如何直接使用 Windows 下字体文件的小 Tip.

Add tips about fonts for wsl users.

---

templates/undergraduate-thesis-en/main.tex
templates/undergraduate-thesis/main.tex

For the undergraduate-thesis(-en).

fix: remove covers in peer review mode.

---

README.md

似乎 inline Math 环境会导致后续的图片无法加载。

fix: fix broken images in README.md

---

bithesis-doc.tex
bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

feat: support hyphenation by default.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: secret info expansion.

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

fix: remove \@@_secret_info:x

---

bithesis-doc.tex
bithesis.dtx
templates/graduate-thesis/main.tex

feat(GT): add support for special type.

---

bithesis.dtx

chore: bump version to 3.7.1

---

bithesis.dtx

chore: update to v3.7.2

---

bithesis-doc.tex
templates/graduate-thesis/misc/4_pub.tex

Relates-to: https://github.com/BITNP/BIThesis/discussions/407#discussioncomment-8630685
Resolves #443
[^1]
[^1]: 手机坏了，连夜备份，没想到还有比编译 LaTeX 更慢的事。

doc: Sort publications

---

bithesis-doc.tex
bithesis.dtx

chore: Make the skips for math env bigger.

---

templates/graduate-thesis/main.tex
templates/paper-translation/main.tex
templates/undergraduate-thesis-en/main.tex
templates/undergraduate-thesis/main.tex

今天又有同学问`abstract.tex`中怎么没有关键词。

doc: 强调关键词应在`main.tex`设置

---

.github/workflows/release.yml

Resolves #389
Relates-to: #493
Resolves #512
> [!TIP]
> 若是初次使用，可先参考**快速使用指南**（[本科][undergraduate-handbook]／[硕博][graduate-handbook]）或者 [Wiki 网站](https://bithesis.bitnp.net/)。有需要再进一步参考[详细配置手册`bithesis.pdf`][bithesis-pdf]。
[undergraduate-handbook]: https://github.com/BITNP/BIThesis/releases/download/v3.7.7/undergraduate-handbook.pdf
[graduate-handbook]: https://github.com/BITNP/BIThesis/releases/download/v3.7.7/graduate-handbook.pdf
[bithesis-pdf]: https://github.com/BITNP/BIThesis/releases/download/v3.7.7/bithesis.pdf
steps.git-cliff.outputs.content

ci: 在发行说明中提示快速使用指南等

---

templates/reading-report/chapters/1_chapter1.tex
templates/undergraduate-thesis/chapters/1_chapter1.tex

其实xeCJK有字体回落机制，设置好后直接输入就行，不用每次换字体。不过生僻字难以稳定测试，无法确定能成功回落，就还是换字体吧。
由群里同学提出。

doc: 更新生僻字使用提示，限制作用范围

---

templates/paper-translation/main.tex

Same as #367.
Relates-to: #350

doc: 在更多地方介绍如何添加水印

---

.github/workflows/release.yml

#493 忘了编译了……
```log
Run actions/upload-artifact@v4
Warning: No files were found with the provided path: the-graduates-handbook/*.pdf. No artifacts will be uploaded.
```
https://github.com/BITNP/BIThesis/actions/runs/9249071070/job/25440328577

ci: 编译快速使用手册

---

bithesis-doc.tex
templates/paper-translation/main.tex
templates/undergraduate-thesis-en/main.tex
templates/undergraduate-thesis/main.tex

doc: 提示更改外文翻译模板的页眉，并更新相关注释

---

bithesis-doc.tex

docs: 改正`misc/algorithmSeparation`的文档

---

.github/ISSUE_TEMPLATE/bug-report-ZH.yaml

docs: 更新 [Bug] 模板

---

bithesis.dtx
templates/graduate-thesis/main.tex

- 对于一般浮动体，只是简单更改数值。
- 对于表格，由于 LaTeX 似乎不支持独立调整表格下方与正文的间距，只好重置`\intextsep`，要另外设计。
Resolves #584
- 左：Word模板
- 右：此PR
<details>
<summary>生成以上截图的源代码</summary>
```diff
diff --git a/templates/graduate-thesis/chapters/chapter1.tex b/templates/graduate-thesis/chapters/chapter1.tex
index 44aeb3e..a53aec1 100644
--- a/templates/graduate-thesis/chapters/chapter1.tex
+++ b/templates/graduate-thesis/chapters/chapter1.tex
@@ -43,25 +43,32 @@
固定相只有物理交联结构的聚氨酯称为热塑性SMPU,而有化学交联结构称为热固性SMPU。热塑性和热固性形状记忆聚氨酯的形状记忆原理示意图如图\ref{fig:diagram}所示
-\begin{figure}[hbt]
- \centering
- \includegraphics[width=0.75\textwidth]{figures/figure1}
- % \caption[这里的文字将会显示在 listoffigure 中]{这里的文字将会显示在正文中}
- \caption{热塑性形状记忆聚氨酯的形状记忆机理示意图}\label{fig:diagram}
-\end{figure}
+根据文献\parencite{Jiang2005Size}，形状记忆聚合物（SMP）是继形状记忆合金后在80年代发展起来的一种新型形状 …
```

fix(GT)!: 参照规定调整浮动体附近的间距

---

bithesis.dtx
templates/graduate-thesis/chapters/abstract.tex

fix(GT): 参照Word模板微调摘要、正文、结论等标题上下的间距，并展示省略号写法

---

README.md

docs: Update README to v3.8.3-alpha-1

---

.github/tl_packages
.github/workflows/test.yaml
.gitignore
Makefile
handbook/chapters/ch0-quick-start.tex
handbook/chapters/ch2-template-usage.tex
handbook/chapters/ch3-latex-syntax.tex
handbook/main.tex
scripts/test.py

Relates to https://github.com/BITNP/BIThesis-wiki/issues/485
CI 从 https://github.com/xu-cheng/texlive-action 换成了 https://github.com/teatimeguest/setup-texlive-action ，前者更早，但后者支持`package-file`，而且 https://github.com/CTeX-org/ctex-kit 也在用。
https://www.star-history.com/#xu-cheng/texlive-action&teatimeguest/setup-texlive-action&Date

ci: Minimize packages

---

.github/tl_packages
.github/workflows/test.yaml
bithesis-doc.tex
scripts/test.py

https://www.internationalphoneticassociation.org/content/ipa-fonts
https://www.internationalphoneticassociation.org/IPAcharts/IPA_chart_orig/pdfs/IPA_Doulos_2020_tooltips.pdf
https://gitlab.com/niruvt/doulossil/-/blob/ed5afec328c6c1e80d02398761f9ebbcc6b07b9c/doulossil.tex#L11-12
https://latex3.github.io/fontspec/user.html
Fix missing characters.
```log
Missing character: There is no ˈ (U+02C8) in font [texgyrecursor-regular.otf]/O
T:script=latn;language=dflt;-liga;!
Missing character: There is no ː (U+02D0) in font [texgyrecursor-regular.otf]/O
T:script=latn;language=dflt;-liga;!
Missing character: There is no ˈ (U+02C8) in font [texgyrecursor-regular.otf]/O
T:script=latn;language=dflt;-liga;!
Missing character: There is no ˈ (U+02C8) in font [texgyrecursor-regular.otf]/O …
```

docs: Fix IPA font

---

.github/workflows/release.yml

ci: 设置测试版的版本号

---

.github/workflows/release.yml

https://github.com/BITNP/BIThesis/releases/tag/v3.8.5-alpha-1

ci: Fix `fd: command not found`

---

.github/workflows/test.yaml
bithesis.dtx

- **style: Fix E300 unexpected function call argument**
- **style: Fix W302 unbraced n-type function call argument**
Resolves #640
已相对 v3.8.4 回归测试，没有区别。

style: Fix LaTeX 3 arguments

---

bithesis.dtx

presentation-slide 除外。
Resolves #634

feat: 允许用 lualatex 编译

---

bithesis-doc.tex
templates/graduate-thesis/misc/4_pub.tex
templates/graduate-thesis/reference/pub.bib

- 更正对`\Author`编号的解释
- 配合 https://github.com/BITNP/BIThesis-wiki/pull/525

docs: 更新`pub.bib`相关文档和注释

---

.github/tl_packages
bithesis.dtx
templates/undergraduate-thesis-en/chapters/0_abstract.tex
templates/undergraduate-thesis-en/main.tex

- **fix(UTE): Add the package datetime2-english**
- **fix(UTE): 改正英文模板中文摘要的首行缩进**
- **docs(UTE): 从中文模板复制注释到英文模板**
Resolves #663

改正英文模板首行缩进

---

templates/graduate-thesis/main.tex

docs(GT): 介绍如何加签名页
