BITNP/BIThesis

wiki/Guide/3-Templates/Final-Graduation-Thesis.md

Due to recent commits, some contents in the graduation thesis wiki are out-dated. This PR fixes those contents and make them up-to-date.
New contents have also be included in this PR. They include:
- How to define external mentor's name and produce external thesis cover;
- How to insert SVG figures into the thesis.

Fix errors in graduation thesis wiki.

---

graduation-thesis/main.tex

Before this PR, sometimes paragraphs may be typesetted as follows which is not acceptable:
This PR addresses this issue and fixes it.
> Note: due to the change of the parameters to the underlying TeX typesetting engine, this commits should be well tested before merging.

Set TeX typesetting parameters to make sure all paragraphs are well typesetted

---

wiki/yarn.lock

This is to address multiple dependency security issues by `yarn upgrade vuepress@^1.4.0`. Note that I haven't had a chance to fully test the vuepress upgrade.

Bump vuepress 1.4.0 to 1.5.4 in /wiki

---

bithesis.dtx

Next time when using the lab-report, the name of working directory won't have to be **lab-report**.

remove parent path reference when using lab-report

---

bithesis.dtx
templates/graduate-thesis/bithesis.cls
templates/paper-translation/bithesis.cls
templates/undergraduate-thesis-en/bithesis.cls
templates/undergraduate-thesis/bithesis.cls

Update overriding code on `\itemcmd`.
We customize the behavior of item indent basically by copying and pasting the upstream code.
Since it's changed recently so the old customized code failed to compile.
Tested both on old and new biblatex-gb7713-2015.
See the changes here:
https://github.com/hushidong/biblatex-gb7714-2015/commit/c41a26a990f0831f00f70f39197c19ca3040c91a
Fix: #160.
Special thanks to @hushidong, @everything411 and @wangzhankun.

fix: mode issue caused by outdated code.

---

Makefile

This PR makes the following works.
```mermaid
flowchart LR
pwsh["PowerShell<br>(of VS Code)"]
--> make["<code>make</code>"]
--> bash["bash<br>(from Git for Windows / MSYS2)"]
```
`$SYSTEMROOT` implies who calls `make`,  not who `make` calls. PowerShell users can [let `make` use bash](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html), and it should work.
Additionally, `$SYSTEMROOT` is about OS rather than the shell. If you call `make` from bash on MSYS2 (on Windows), then `$SYSTEMROOT` also exists, but `del` doesn't.
Moreover, Command Prompt's `del` cannot understand `-r`.
---
Relevant: #180

Make `rm` can work on Windows (really)

---

bithesis.dtx

Fonts installed by TeXLive cannot be found via font names on macOS.

fix: set font by font file names (in stead of font names).

---

.gitignore
DEVELOPMENT.md
Makefile
scripts/regression-testing.ps1

Windows 上使用 make 甚至 bash 都有可能，但 zsh 恐怕不太行，所以翻译成了`scripts/regression-test.ps1`。
- PowerShell 有`ConvertFrom-Json`，无需 jq。（虽然 jq 也很容易安装）
- `.gitignore`中不能忽略`scripts/`目录，不然后续`!`无效。
Relates-to: #180

build: PowerShell version of regression-test

---

README-bithesis.md
README.md

[jwc](https://jwc.bit.edu.cn)（教务部）→ [jwb](https://jwb.bit.edu.cn)（教务部）。大概2023年3月改的。旧站仍在线，但只是部分正常。

doc: 更新教务部网站

---

bithesis.dtx

- 包了一下`\color`。
- 把`\newcommand`改成了`\newenvironment`。不是很懂原来为什么能当 environment 用……
Fixes #375

fix: note environment does not work as expected

---

.github/ISSUE_TEMPLATE/release-tracker.md

`CHANGLOG` → `CHANGELOG`. (-E-)

fix: typo in release-tracker.md

---

bithesis-doc.tex

doc: Unify the case of “GitHub”

---

bithesis.dtx

参照2023年12月相关通知修改封面：
- 微调`\vspace`。
- “外文原文题目：”和“中文翻译题目：”改为宋体。
[`undergraduate-thesis`及`paper-translation`与2023年模板的区别 · Discussion #396](https://github.com/BITNP/BIThesis/discussions/396) 提到的其它区别我不打算改了；PT 主要是字体变了，改一下。
回归测试：
另外，调试时用到了以下脚本，以后可能有用。
```pwsh
Push-Location ../..
make cls
Pop-Location
toastify send BIThesis "✅ bithesis.cls"
Copy-Item ../../bithesis.cls
latexmk
toastify send BIThesis "✅ main.pdf"
diffpdf ./main.pdf ./ref.pdf
```

fix: Update styles of PT

---

bithesis.dtx

外文翻译封面有两组中英文标题，行数变化范围大（可能相差3行），行太多时会挤到下一页。为避免这种可能，采用`fill`比例布局。
其它模板的学院、专业也可能加行，但版面没这么紧，所以没改。
历史：@CZLeader 用了 https://github.com/BITNP/BIThesis/releases/tag/v3.6.1 ，四个标题都占两行，“指导教师”会挤到第二页。在发布的版本之后，#399 (f32503b) 改了这个间距，这个问题仍存在，且更容易被触发了。
<details>
<summary>学校 Word 模板也有这个问题</summary>
</details>
（有对话框的是学校 Word 模板）
[spacing - Lengths and when to use them - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/41476/lengths-and-when-to-use-them)

refactor: Stretch spaces in the cover of PT

---

bithesis.dtx

Fixes #410
这个做法在`biblatex`和`biblatex-gb7714-2015`的手册里有，并不是很hack。
`templates/graduate-thesis/main.tex`：设置盲审模式，显示3个作者（国标要求只显示1个，但想显示自己）。
```diff
-\documentclass[type=master,twoside]{bithesis}
+\documentclass[type=master,twoside,blindPeerReview=true]{bithesis} % 或者false
\BITSetup{
@@ -90,7 +90,7 @@
% 一般来说，如果你在全部文献中最低排在第四位，建议你将两个值都设置为 4。
% 更详细的说明请见手册。
maxbibnames = 3,
-    minbibnames = 1,
+    minbibnames = 3,
},
```
`templates/graduate-thesis/reference/pub.bib`：多加些作者。
```diff
@article{myCiteKey,
title = {交联型与线形水性聚氨酯的形状记忆性能比较},
-  author = {张三 and 李杰 and 罗运军},
+  author = {张三 and 李杰 and 罗运军 and 汪淼},
author+an = {1:myself="\Author"},
@@ -80,7 +80,7 @@
}
@book{dummy:2,
-  author = "John Doe and San Zhang",
+  author = "John Doe and San Zhang and White Ice and AAA",
author+an = …
```

fix: Remove `, et al.` etc. for `pub.bib` in `blindPeerReview` mode

---

CHANGELOG.md
DEVELOPMENT.md
Makefile
bithesis.dtx

Release v3.6.3

---

.github/ISSUE_TEMPLATE/release-tracker.md
.github/workflows/release.yml
DEVELOPMENT.md
Makefile

- **触发条件**：发布正式 release。
- **功能**：下载`.github/workflows/release.yml`中`build`上传的手册，打包，上传到CTAN。
- **版本号**：发布 release 时从 tag name 提取。
之前运行记录：
- 触发条件：https://github.com/YDX-2147483647/BIThesis/releases/tag/v3.7.0-alpha.0
- 结果：https://github.com/YDX-2147483647/BIThesis/actions/runs/8415011474/attempts/1#summary-23039595164
Relates-to: #425 
<details>
<summary>旧版</summary>
https://github.com/BITNP/BIThesis/commit/bbe373d367925522e62f870cdb4a8a79872ea4dd
- **功能**：下载`.github/workflows/release.yml`上传的手册，打包，上传到CTAN。
注意手册是从 artifact 下载，并不会重新编译。
- **触发条件**：发布 release 或手动触发。
- **版本号**：发布 release 时从 tag name 提取（尚未测试），手动触发时人为指定。
文件中还实现了从最后一次 release 提取 tag name，仅为备用，正常会跳过。
之前运行记录： https://github.com/YDX-2147483647/BIThesis/actions/workflows/ctan.yml
Relates-to: #425 
“Upload to CTAN”这步的`action: …

CI: Upload to CTAN and minor fixes

---

bithesis-doc.tex
bithesis.dtx

- 增加调整浮动体与正文间距的选项
- 本科生模板补充当图片或表格在页面顶端或底端时的空行
- 研究生模板要求图表序和图表题之间空1个中文字距
- 更新文档
- 当浮动体位于顶端和底端时仅改变浮动体与正文的间距
- misc / floatSeparation = 0 即保持默认
- misc / floatSeparation = -1
- misc / floatSeparation = 2.5
- 修改前
- 修改后
- `lstlisting` 也相应处理

feat: control separation around float environment

---

bithesis.dtx

修复默认显示为「Algorithm」的算法环境。
1. 从原有的标准字号改为 caption 采用的 `\small` 字号。
2. 英文「Algorithm」改为中文「算法」。
3. 修复 `\autoref` 引用算法时的名称。

fix: standardize algo ref name.

---

bithesis-doc.tex
bithesis.dtx

Based on [captions - Modifying the algorithm name in algorithm2e - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/541495/modifying-the-algorithm-name-in-algorithm2e/541499#541499)
Resolves #454
Relates-to: #445
无论是否使用`algorithm2e`，标题、autoref、分隔符都正常，并且不影响模板原有的`algo`。
```latex
\usepackage[ruled,algochapter]{algorithm2e}
\mainmatter
\begin{algo}
啊
\end{algo}
\begin{algorithm} 
\SetKwData{Left}{left}\SetKwData{This}{this}\SetKwData{Up}{up} \SetKwFunction{Union}{Union}\SetKwFunction{FindCompress}{FindCompress} \SetKwInOut{Input}{输入}\SetKwInOut{Output}{输出}
\Input{A bitmap $Im$ of size $w\times l$}
\Output{A partition of the bitmap}
\BlankLine
\emph{special treatment of the first line}\;
\For{$i\leftarrow 2$ \KwTo $l$}{
\lForEach{element $e$ of the line …
```

fix: support the `algorithm2e` package

---

bithesis.dtx

[`tabularx`](https://www.ctan.org/pkg/tabularx)基本是指定列宽的唯一选择——`tabular*`只能指定空白宽度。它由 The LaTeX Project Team 维护，也被 [Overleaf 文档](https://www.overleaf.com/learn/latex/Tables)收录了，比较著名，应当适配。
```latex
\BITSetup{
misc = {
tabularFontSize = 0,
}
}
\usepackage{tabularx}
% 钩子挂在这里了，必须有。
\frontmatter
\begin{table}[ht]
\begin{tabularx}{\textwidth}{|X|}
\hline
初号字 Font size 0 \\
\hline
\end{tabularx}
\end{table}
正文
{\zihao{0} 初号字 Font size 0}
\end{document}
```

fix: 改正`tabularx`环境中的字号

---

templates/paper-translation/chapters/1_chapter1.tex
templates/reading-report/chapters/1_chapter1.tex
templates/undergraduate-thesis-en/chapters/2_chapter2.tex
templates/undergraduate-thesis/chapters/1_chapter1.tex

9e58b8b 在`tabular`环境开头改了字号，所以在`tabular`外设置字号不会影响表格内部。另外`\captionsetup[table]{font=small,…}`也将标题设为了小五号。
模板提供了`misc/tabularFontSize`统一设置`tabular`和`tabular*`的字号，默认是`5`。
例如，下面设置`\zihao{0}`，但并未改为初号。

refactor: 删除表格中无用的`\zihao{5}`

---

bithesis-doc.tex
bithesis.dtx

refactor: 只在按章编号时适配algorithm宏包

---

bithesis.dtx

fix: `\usepackage[chapter]{algorithm}`时开头不应出现“algorithm2ealgochaper”字样

---

bithesis-doc.tex
bithesis.dtx
templates/paper-translation/chapters/1_chapter1.tex
templates/paper-translation/main.tex
templates/reading-report/chapters/1_chapter1.tex
templates/reading-report/main.tex
templates/undergraduate-thesis-en/chapters/2_chapter2.tex
templates/undergraduate-thesis-en/main.tex
templates/undergraduate-thesis/chapters/1_chapter1.tex
templates/undergraduate-thesis/main.tex

#396 已注意到这一问题，当时认为不重要。昨天有同学说他们组专门提出来了，只好改一下。
具体的修改请看提交信息。
- 表格caption不再有空隙，直接紧贴。
- 表格每行变窄一些。
只影响本科模板，且不改变表格前后间距。

微调本科模板表格格式

---

.github/workflows/release.yml

- `update_changelog` → `release_notes`以免混淆。
- `git commit` → PR 以绕开分支保护。
Fixes #478
没有测试过，不过恐怕只能实际试验了。

ci: Fix changelog

---

bithesis-doc.tex
bithesis.dtx

Fixes #498 
Relates to #501 
TODO：longtable表格上框线和caption有多余间距。
<details>
<summary>过时测试结果</summary>
下图左边将`tabularRowSeparation`设为`1.25`，右边设为`1`，可见表格受影响，而矩阵不变。
下图设为`1.25`，可见三种表格都能改。
</details>
- 字号影响`tabular`、`tabular*`、`tabularx`、`longtable`的内容，不影响caption。
- 各行间距影响`tabular`、`tabular*`、`tabularx`，不影响`longtable`（它自己已改）、矩阵。
```latex
% !BIB program = biber
\BITSetup{
misc = {
tabularRowSeparation = 1.25,
% tabularFontSize = 8,
},
}
\usepackage{tabularx}
\usepackage{longtable}
\frontmatter
\mainmatter
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
\begin{equation}
\begin{bmatrix}
1 & 0 \\
1 & 0 \\
1 & 0 \\
1 & 0 \\
\end{bmatrix}
\end{equation}
\begin{table}[ht]
\centering
\caption{Tabular} …
```

fix: `misc/tabularRowSeparation`不应影响矩阵

---

templates/undergraduate-thesis-en/main.tex

之前没有注释，让群里同学以为要改`\BITSetup`的`cover/hideCoverInPeerReview`了。
Relates-to: #496
Relates-to: 670c3fc40d6d6dfed329977917d2d77f8ab36598

doc: 给本科英文模板添加盲审模式注释

---

bithesis-doc.tex
bithesis.dtx

针对algorithm2e宏包，添加`misc/algorithmSeparation`选项，可供调整算法与文字之间的距离。
与之前版本相比，默认间距会从约3点增大到约12点。
Fixes #494
algorithm2e宏包原本的默认值相当于`\smallskip`，此PR的默认值相当于`\bigskip`。
根据`texdoc source2e`，在 LaTeX 中，这些 skip 用`\vspace`实现。
```latex
\def\smallskip{\vspace\smallskipamount}
\def\bigskip{\vspace\bigskipamount}
\newskip\smallskipamount \smallskipamount=3pt plus 1pt minus 1pt
\newskip\bigskipamount \bigskipamount =12pt plus 4pt minus 4pt
```
其中`12pt plus 4pt minus 4pt`表示以`12pt`为基准，允许上下浮动`4pt`。
旧版：
默认：
设为`5em`：
```latex
\BITSetup{
misc = {
algorithmSeparation = {5em},
},
}
\usepackage[ruled, algochapter]{algorithm2e}
在这里添加第二章、第三章……TeX 文件的引用
在这里添加第二章、第三章……TeX 文件的引用
在这里添加第二章、第三章……TeX 文件的引用
在这里添加第二章、第三章……TeX 文件的引用
在这里添加第二章、第三章……TeX 文件的引用
在这里添加第二章、第三章……TeX …
```

feat: 调整算法与文字之间的距离（针对algorithm2e宏包）

---

bithesis.dtx

Resolves #505
```latex
% !BIB program = biber
\documentclass[type=master]{bithesis}
\BITSetup{
info = {
author = {杜甫},
% title = 八月秋高风怒号卷我屋上三重茅茅飞渡江洒江郊高者挂罥长林梢下者飘转沉塘坳,
title = 形状记忆聚氨酯的合成及其在织物中的应用,
% verticalTitle = {形状记忆聚氨酯{L } {T } {X }的合成 \rotatebox[origin=c]{-90}{Feng Kaiyu} 及其在织物中的应用},
},
}
\MakePaperBack
\end{document}
```
- `old.pdf`：旧版
- `new.pdf`：此PR
- 其它PDF：Word模板
29.7 mm / 941 × 158 = 5.0 mm.
- `\vskip` → `\newgeometry` + `\restoregeometry`
原来的`\vskip`没生效（删掉后编译结果相同），而且需要从上边距开始算。干脆改边距好了。
- `center`环境 → `\centering`
lshort-zh-cn：`center`等环境会在上下文产生一个额外间距，而`\centering`等命令不产生，只是改变对齐方式。
- `minipage`环境的对齐方式 `t` → `c`
这样遇到超长标题时，可以向两边溢出。
- `\vfill` → `\par` + `\vpace`
`\vspace`可以设置间距最小值，避免标题稍长就和姓名学校粘在一起。
另外，`\vfill`会直接生效，而`\vspace`不会，所以要加`\par`。

refactor: 让硕博模板书脊上下居中，并适应长标题，避免与姓名粘连

---

bithesis-doc.tex
bithesis.dtx

继续 #499 和 #504。
https://github.com/BITNP/BIThesis/issues/501#issuecomment-2130053861
https://github.com/BITNP/BIThesis/issues/501#issuecomment-2132080016
它似乎不受`\textfloatsep`等控制。
```latex
\BITSetup{
misc/floatSeparation = -1.5, % 仅测试，随意指定的
misc/tabularRowSeparation = 1.25, % 本科表格行高
}
```
设置
```latex
% !BIB program = biber
% \BITSetup{
%   misc/floatSeparation = -1.5,
%   misc/tabularRowSeparation = 1.25,
% }
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{zhlipsum}
\frontmatter
\mainmatter
\zhlipsum[1][name=zhufu]
\begin{table}[ht]
\centering
\caption{Tabular Lg} % 都含“Lg”两个伸长的字母，控制变量
\begin{tabular}{*{5}{>{\centering\arraybackslash}p{5em}}}
\toprule
项目    & 产量    & 销量    & 产值   & 比重    \\ \midrule …
```

feat: 适配`longtable`宏包

---

bithesis.dtx
templates/undergraduate-thesis-en/main.tex

* 在本科全英文模板编译出的PDF书签中，会同时出现"目录"和"Table of Content"，似乎是 #480 引入的Bug。
* 在全英文模板`main.tex`中添加了title属性，以此在中文摘要中输出正确标题。修复了样例中的"Bachelor"拼写错误。

fix: remove redundant `\currentpdfbookmark` for English bachelor thesis

---

bithesis-doc.tex
templates/graduate-thesis/reference/pub.bib

之前完全没有提到`\Author`与`\AuthorEn`的区别，导致个别同学复制错了例子。

doc: 补充介绍`\AuthorEn`

---

bithesis-doc.tex
bithesis.dtx
templates/undergraduate-thesis-en/main.tex
templates/undergraduate-thesis/main.tex
the-graduates-handbook/chapters/ch2-example-bachelor-blind.tex
the-graduates-handbook/chapters/ch2-example-master-blind.tex
the-graduates-handbook/chapters/ch2-template-usage.tex

Resolves #533
<details>
<summary>其它方案</summary>
更新文档时发现模板已经有别的地方在`.initial`实现了“自动按论文类型设置初始值”：
https://github.com/BITNP/BIThesis/blob/cad285745fb2482f0f41d4d6b8814ae59a3f7359/bithesis.dtx#L819-L824
https://github.com/BITNP/BIThesis/blob/cad285745fb2482f0f41d4d6b8814ae59a3f7359/bithesis.dtx#L526-L535
要改成这样吗？
</details>

盲评相关文档、自动设置`hideCoverInPeerReview`

---

bithesis-doc.tex
bithesis.dtx

Resolves #500
如需恢复数学行距至原先的中文水平，可在导言区将倍数从1调大至1.53：
```latex
\SetMathEnvironmentSinglespace{1.53}
```
如下图，减小了数学公式中矩阵的行距，不改变正文行距和段落间距。
```latex
\chapter{MWE}
中华民国十五年三月二十五日，就是国立北京女子师范大学为十八日在段祺瑞执政府前遇害的刘和珍杨德群两君开追悼会的那一天，我独在礼
堂外徘徊，遇见程君，前来问我道，“先生可曾为刘和珍写了一点什么没有？”我说“没有”。她就正告我，“先生还是写一点罢；刘和珍生前就
很爱看先生的文章。”
这是我知道的，凡我所编辑的期刊，大概是因为往往有始无终之故罢，销行一向就甚为寥落，然而在这样的生活艰难中，毅然预定了《莽原》
全年的就有她。我也早觉得有写一点东西的必要了，这虽然于死者毫不相干，但在生者，却大抵只能如此而已。倘使我能够相信真有所谓“在
天之灵”，那自然可以得到更大的安慰，——但是，现在，却只能如此而已。
她的姓名第一次为我所见，是在去年夏初杨荫榆女士做女子师范大学校长，开除校中六个学生自治会职员的时候。其中的一个就是她；但是我
不认识。直到后来，也许已经是刘百昭率领男女武将，强拖出校之后了，才有人指着一个学生告诉我，说：这就是刘和珍。其时我才能将姓名
和实体联合起来，心中却暗自诧异。我平素想，能够不为势利所屈，反抗一广有羽翼的校长的学生，无论如何，总该是有些桀骜锋利的，但她
却常常微笑着，态度很温和。
\begin{equation}
\begin{bmatrix}
1 & 2 & Af \\
3 & 4 & fA \\
\end{bmatrix}
\end{equation} …
```

feat: 改小数学行距至西文水平

---

bithesis-doc.tex
bithesis.dtx
templates/paper-translation/main.tex
templates/reading-report/main.tex
templates/undergraduate-thesis-en/README.md
templates/undergraduate-thesis-en/chapters/0_abstract.tex
templates/undergraduate-thesis-en/main.tex
templates/undergraduate-thesis/main.tex

更改繁杂，请查看提交记录。
Resolves #496
- ~~引入了若干只有个别模板适用的选项。选项不适用时，也许有必要[用 l3msg 警告](https://tex.stackexchange.com/questions/246810/latex3-l3msg-best-practices)？~~ 大约一般人不会凭空加选项。
- ~~问一下经管学院的同学。~~ 太久没回复。
[diff.pdf](https://github.com/user-attachments/files/16179682/diff.pdf)
[经管学院版](https://github.com/user-attachments/files/16179806/main.pdf)

更新本科英文模板以及相关内容

---

.github/workflows/release.yml

name 用于 URL，不能有汉字，但 display label 可以。
https://github.com/BITNP/BIThesis/pull/493#discussion_r1592214482
https://github.com/adobe-fonts/source-han-serif/releases/tag/2.002R 就采用了这种方式。
- 大部分上传改用 [GitHub CLI](https://cli.github.com/manual/gh_release_upload)，因为原来的 actions 似乎不支持指定 label，而且`gh release upload`更简单。
- 中文显示名参考了[网站][wiki]。
- 除`bithesis.pdf`外都标注了。
Relates-to: #389
[wiki]: https://github.com/BITNP/BIThesis-wiki/blob/ee2c335682486359e31a25cbb11fc77d909a0a42/wiki/guide/preface.md#qbithesis-%E9%83%BD%E5%8C%85%E5%90%AB%E5%93%AA%E4%BA%9B%E6%A8%A1%E6%9D%BF

ci: 标注中文显示名

---

bithesis-doc.tex
bithesis.dtx

重新实现了 #533 的 286fa7003888dfd65686925fef1d3ee519b714b4。当时只验证了本科模板，没想到由于 LaTeX 的奇葩机制，误改了硕博模板。
Fixes #548
| `\documentclass[type = …]{bithesis}` | `\BITSetup{…}`                        | `\l_@@_cover_hide_cover_in_peer_review_bool` |
| ------------------------------------ | ------------------------------------- | -------------------------------------------- |
| `master`                             | 空 | false（此PR前是true，之前发布版是false）                 |                                              
| `master`                             | `cover/hideCoverInPeerReview = false` | false                                        |
| `master`                             | `cover/hideCoverInPeerReview = true`  | false → true                                 |
| `bachelor`                           | 空 …

fix: 硕博模板中`cover/hideCoverInPeerReview`应仍默认为 false

---

.github/workflows/release.yml

之前 https://github.com/BITNP/BIThesis/releases/tag/v3.7.10-alpha-1 的内容是 v3.7.9，对不上。现在针对 pre-releases 从`--latest`改用`--unreleased`。
```bash
$ git cliff --help
…
-l, --latest          Processes the commits starting from the latest tag
--current         Processes the commits that belong to the current tag
-u, --unreleased      Processes the commits that do not belong to a tag
…
```
参考了 https://github.com/search?q=orhun%2Fgit-cliff-action+path%3A.github%2Fworkflows%2F+language%3AYAML+repo%3Aratatui%2Fratatui&type=code&s=indexed&o=desc ，他们`release-alpha.yml`采用`--unreleased`，`release-stable.yml`采用`--latest`。

ci: Fix release notes of pre-releases

---

bithesis-doc.tex
bithesis.dtx
templates/undergraduate-thesis-en/README.md

* 在本科毕设英文模板封面（英文模式）中的英文标题之上增加了中文标题，以符合论文抽检系统要求。

feat: 本科毕设英文模板封面按照要求加入中文标题

---

bithesis-doc.tex
handbook/chapters/ch2-example-pub.bib
handbook/chapters/ch2-template-usage.tex
templates/graduate-thesis/misc/4_pub.tex

- **doc(handbook): 增加链接**
- **doc: 改进「攻读学位期间发表论文与研究成果清单」相关文档**

doc: 改进几处文档

---

templates/graduate-thesis/main.tex
templates/undergraduate-thesis-en/main.tex

`\BITSetup`（l3keys）使用`,`分隔。如果标题本身就含`,`，必须用括号包裹，不然无法正常解析。
这并不显然。给示例加上括号，可以让一般人也能猜到。
（今天群里有人问，上学期我也被别人问过。）
<details>
<summary>Typst 的样子</summary>
[charged-ieee – Typst Universe](https://typst.app/universe/package/charged-ieee)
```typst
#import "@preview/charged-ieee:0.1.3": ieee
#show: ieee.with(
title: [A typesetting system to untangle the scientific writing process],
abstract: [
The process of scientific writing is often tangled up with the intricacies of typesetting, leading to frustration and wasted time for researchers. In this paper, we introduce Typst, a new typesetting system designed specifically for scientific writing. Typst untangles the typesetting process, allowing researchers to compose papers faster. In a series of experiments we demonstrate that Typst offers several …
```

docs: 给`titleEn`示例添加括号

---

DEVELOPMENT.md
bithesis.dtx

- 删除了`bithesis.dtx`中不匹配的`\begin{macro}`（[`1be9eb7`](https://github.com/BITNP/BIThesis/commit/1be9eb7) 引入）
之前会报错。
```log
./bithesis.dtx:45: LaTeX cmd Error: Verbatim-like environment 'macro' illegal i
n argument.
For immediate help type H <return>.
...
l.45 % \section
{实现细节}
```
- 介绍 DocStrip。

docs: 更新开发文档

---

bithesis.dtx

Fixes #589
Fixes #338 (again)
Relates to #445
1. 本科模板中，`代码 2.1`（再次）改正为`代码 2-1`。
2. `misc/autoref/algo`选项仍然正常。
```latex
\BITSetup{ misc / autoref / algo = {所谓“算法”} }
\usepackage[ruled, algochapter]{algorithm2e}
```
```latex
\begin{algorithm}
\caption{An algorithm with caption}\label{alg:two}
$i\gets 10$\;
\eIf{$i\geq 5$}
{
$i\gets i-1$\;
}{
\If{$i\leq 3$}
{
$i\gets i+2$\;
}
}
\end{algorithm}
```

fix: listings 代码编号中的分隔标签

---

bithesis.dtx

之前用了负间距，太 hack 了，有时文字都会被遮住。
https://github.com/BITNP/BIThesis/issues/584#issuecomment-2746187155
Resolves #584 (again)

 fix(GT): 浮动体连续排列时的间距不能过窄

---

bithesis-doc.tex
bithesis.dtx

- **docs: 更正文档类组成**
↑新 ↓旧
- **docs: Fix 24 warnings**
- LaTeX Warning: Label … multiply defined.
- LaTeX Warning: No positions in optional float specifier.
- Package Listings Warning: Text dropped after begin of listing on input line …
- 只剩余字体问题。

docs: 更正文档类组成、修复警告

---

.github/tl_packages
scripts/test.py

Resolves https://github.com/BITNP/BIThesis/pull/607#issuecomment-2775919346
之前测试时在逐步缩小范围，但有缓存。有些关键宏包即使被删除了，缓存里也有，所以仍能编译。
<details><summary>测试脚本</summary>
```patch
From f6079c6cec99b856d56abbf0848f1a821f6e0c44 Mon Sep 17 00:00:00 2001
From: "Y.D.X." <73375426+YDX-2147483647@users.noreply.github.com>
Date: Thu, 3 Apr 2025 23:59:40 +0800
Subject: [PATCH] temporary scripts
---
Makefile                     |  2 +-
packages.txt                 | 50 ++++++++++++++++++++++++++++++++++++
scripts/minimize_packages.py | 31 ++++++++++++++++++++++
scripts/test.py              | 20 +++++++--------
4 files changed, 92 insertions(+), 11 deletions(-)
create mode 100644 packages.txt
create mode 100644 scripts/minimize_packages.py
diff --git a/Makefile b/Makefile
index 973a2c4..fc0a1a1 100644
--- a/Makefile …
```

ci: Fix packages

---

bithesis.dtx

Fixes #608
Co-authored-by: https://github.com/Aaron-Gp
解释请见 https://github.com/BITNP/BIThesis/issues/608#issuecomment-2774606929 。
完全没变化……因为默认的`cover/autoWidthPadding`体现不出来。

fix: 调大`cover/autoWidthPadding`时，题名页信息应该整体居中

---

bithesis.dtx

Fixes #613
```latex
% \documentclass[type=bachelor]{bithesis}
\documentclass[type=master]{bithesis}
\BITSetup{
info = {
title = 国国国口口口口口口口口国国国,
author = 张三,
school = 材料学院,
supervisor = 李四教授,
chairman = 王五教授,
industrialMentor = 李五教授,
degree = { 材料与化工 \\ 博士 },
major = 材料工程,
},
}
% \MakeCover
\MakeTitle
\end{document}
```
<details>
<summary>截图</summary>
</details>
1584719 让本科模板又偏右了……
<details>
<summary>截图</summary>
</details>
原因在于本科有六字的`校外指导教师`，通常不显示，但仍计入了`\@@_get_max_text_width:NN`。
https://github.com/BITNP/BIThesis/blob/3c5e39729497701ec52d70691058bffe99cd02d6/bithesis.dtx#L490
https://github.com/BITNP/BIThesis/blob/3c5e39729497701ec52d70691058bffe99cd02d6/bithesis.dtx#L2540
```latex
\clist_set:Nn \l_@@_input_clist {
{项目} {内容内容内容},
{不存在不存在} {},
} …
```

fix: 封面信息整体应居中

---

bithesis.dtx

Resolves #617
“行距的改变直到文字分段时才生效”，之前缺`\par`，没设置上。
目前行距还是比 Word 模板略小；还需要再调大吗？

fix(GT): 封皮、题名页标题的行距不应过小

---

Makefile
bithesis-doc.tex
bithesis.dtx

- **feat: 支持在PDF书签中隐去封面、书脊、题名页、声明，如`\MakeCover[bookmarked = false]`**
- **docs: 改进 DocStrip 里的文档**
- **feat: 支持用`title`修改`conclusion`环境内的标题**
Resolves #623
这次的选项只控制局部，键值对直接挂了命令上，没有挂到`\BITSetup`。
设计参考了`texdoc interface3`。
<details>
<summary>interface3.pdf 节选</summary>
```latex
\MyModuleMacro[
key-one = value one,
key-two = value two
]{argument}
```
```latex
\DeclareDocumentCommand \MyModuleMacro { o m }
{
\group_begin:
\keys_set:nn { mymodule } { #1 }
% Main code for \MyModuleMacro
\group_end:
}
```
</details>
`make regression-test args='--against main-c97d797'`没有区别。
```latex
\MakeCover[bookmarked = false]
\MakePaperBack[bookmarked = false]
\MakeTitle  % 默认 bookmarked = true
\MakeOriginality[bookmarked = …
```

 feat: 支持隐去PDF书签，支持修改结论标题

---

CHANGELOG.md
cliff.toml

```log
WARN  git_cliff_core::changelog > Variables ["commit.github", "commit.gitea", "commit.gitlab", "commit.bitbucket"] are deprecated and will be removed in the future. Use `commit.remote` instead.
```

ci(git-cliff): 修正时区，更新配置

---

bithesis.dtx
tests/l3msg-warning/main.tex

fix: TeX Live 2022/2023 或更早版本无法发出警告

---

bithesis.dtx

群里有人遇到关键词被挤到下一页，只好在`abstract`环境内`\vspace{-4ex}`。
<details><summary>测试用例</summary>
```latex
\usepackage{lipsum}
\usepackage{zhlipsum}
\frontmatter
\begin{abstract}
\zhlipsum[1-2]
当我沉默著的时候，我觉得充实；我将开口，同时感到空虚。
\end{abstract}
\begin{abstractEn}
\lipsum*[1-3]
Do you here the people sing?
Singing a song of angry men?
\end{abstractEn}
\end{document}
```
```latex
\documentclass[type=master]{bithesis}
\usepackage{lipsum}
\usepackage{zhlipsum}
\frontmatter
\begin{abstract}
\zhlipsum[1-2]
当我沉默著的时候，我觉得充实；我将开口，同时感到空虚。
过去的生命已经死亡。我对于这死亡有大欢喜，因为我借此知道它曾经存活。死亡的生命已经朽腐。我对于这朽腐有大欢喜，因为我借此知道它还非空虚。
生命的泥委弃在地面上，不生乔木，只生野草，这是我的罪过。
\end{abstract}
\begin{abstractEn}
\lipsum*[1-3]
Do you here the people sing?
Singing a song of angry men?
It is the …
```

feat: 给摘要页竖直间距增加弹性，允许写更多内容

---

bithesis.dtx
scripts/test.py

1. 没问题时正常编译
2. 内容超长时发出警告并提示换行
3. 换行后消除警告
4. 盲审模式`***`长度固定，无此问题
<details><summary>截图</summary>
</details>
Resolves BITNP#649
已相对 v3.8.4 回归测试，没有区别。

fix: 限制盲审模式题名页`***`长度，以防行溢出

---

.github/lychee.toml
.github/workflows/test.yaml

CHANGELOG 有许多 GitHub 上的提交链接，导致 429 Too Many Requests。
之前没问题，可能是因为缓存没过期，一点一点加上去，每次量不大。

ci(check-links): Ignore CHANGELOG

---

bithesis.dtx

英文标题在英文模板比在中文模板大，所以没有照抄中文模板的参数。
Resolves #665
```latex
\documentclass[type=bachelor_english]{bithesis}
\BITSetup{
cover = {
headerImage = images/header.png,
xiheiFont = STXIHEI.TTF,
},
info = {
title = {证明费马定理 \\ 即所有 $4n + 1$ 形式的质数 \\ 都是两个平方数之和},
titleEn = {Proof of Fermat's theorem \\ that every prime number of the form $4n + 1$ \\ is the sum of two squares},
school = Acta Novi Commentarii academiae \\ scientiarum Petropolitanae,
major = {Demonstratio theorematis Fermatiani omnem numerum primum \\ formae $4n + 1$ esse summam  duorum quadratorum},
author = Leonhard Euler,
studentId = {E241, 1760},
supervisor = Mark R. Snavely and Phil Woodruff,
},
}
\MakeCover
\end{document}
```

fix(UTE): 给题名页间距增加弹性，以容纳更多内容

---

bithesis.dtx

```latex
\documentclass[type=master,twoside=false]{bithesis}
\BITSetup{
info = {
title = 形状记忆聚氨酯的合成及其在织物中的应用,
author = 张三,
studentId = 31xxxxxxxx,
school = 材料学院,
},
}
\MakeCover
\end{document}
```

fix(GT): `\MakeCover`应避让封皮预置内容
